// Amazon product identifiers are fixed to specific listings; prices and availability live on Amazon.
const products=[
{asin:'B014PFS2VE',name:'Slicker Brush',category:'Coat care',icon:'🪮',detail:'A brush for routine coat care between grooming visits.'},
{asin:'B08PCZT5VZ',name:'Greyhound-Style Grooming Comb',category:'Coat care',icon:'✨',detail:'A metal comb for checking the coat after brushing.'},
{asin:'B01ARX4LRC',name:'Rubber Shedding Brush',category:'Coat care',icon:'🐕',detail:'A rubber brush to help collect loose fur.'},
{asin:'B09Y788BPW',name:'FURminator deShedding Conditioner',category:'Bath time',icon:'🧴',detail:'Conditioner to add to a wash-day routine.'},
{asin:'B08QJNMHLZ',name:'Dog Toothbrushing Kit',category:'Paws & teeth',icon:'🦷',detail:'A toothbrush and pet toothpaste kit for home care.'},
{asin:'B01MSN3ZLW',name:'Moisturizing Paw Balm',category:'Paws & teeth',icon:'🐾',detail:'An option for caring for dry paw pads.'},
{asin:'B005CUTWDE',name:'Wahl Oatmeal Dog Shampoo',category:'Bath time',icon:'🫧',detail:'Oatmeal shampoo for bath time.'},
{asin:'B0879DQHPL',name:'Dog Nail Clipper Set',category:'Paws & teeth',icon:'✂️',detail:'Nail care tools for confident home trims.'},
{asin:'B0002DK09G',name:'Small Dog Nail Clippers',category:'Paws & teeth',icon:'🐶',detail:'A small clipper option for petite pups.'},
{asin:'B0002H3RBU',name:'Kwik Stop Styptic Powder',category:'Paws & teeth',icon:'🩹',detail:'A useful standby when trimming nails.'},
{asin:'B00KAKFR7Q',name:'Chris Christensen Big G Slicker Brush',category:'Coat care',icon:'🪮',detail:'A slicker brush for longer, curly coats and regular detangling.'},
{asin:'B00ZGPI3OY',name:'Hertzko Self-Cleaning Slicker Brush',category:'Coat care',icon:'🐕',detail:'A push-button slicker brush that makes cleanup easy.'},
{asin:'B07MZDTG76',name:'FURminator Large Dog Long-Hair Tool',category:'Coat care',icon:'✨',detail:'An undercoat tool for large, long-haired dogs; check the fit for your pup.'},
{asin:'B01FE3IIC4',name:'Bodhi Dog Bath Brush',category:'Bath time',icon:'🫧',detail:'A soft bath-time scrubber to work shampoo through the coat.'},
{asin:'B00LNEDDLA',name:'Earthbath Oatmeal & Aloe Shampoo',category:'Bath time',icon:'🛁',detail:'A dog shampoo option for an at-home bath.'},
{asin:'B0733Q6FZS',name:'Earthbath Oatmeal & Aloe Shampoo + Conditioner',category:'Bath time',icon:'🧴',detail:'A coordinated wash-and-condition set for bath day.'},
{asin:'B08YGYMFVZ',name:'Burt’s Bees Tearless Puppy Shampoo',category:'Bath time',icon:'🐶',detail:'A gentle puppy shampoo; see Amazon for the current size and options.'},
{asin:'B0002IJQDC',name:'Musher’s Secret Paw Wax',category:'Paws & teeth',icon:'🐾',detail:'A paw balm for dry pads and outdoor walks.'},
{asin:'B00RZDXA7K',name:'Virbac C.E.T. Enzymatic Toothpaste',category:'Paws & teeth',icon:'🦷',detail:'Pet toothpaste for a home dental-care routine.'},
{asin:"B00OIOB90E",name:"GoPets 2-in-1 Dematting Comb",category:"Coat care",icon:"🪮",detail:"A double-sided tool for coat maintenance."},
{asin:"B00VC8DQX2",name:"SleekEZ Dog Shedding Tool",category:"Coat care",icon:"🐕",detail:"A tool for collecting loose hair."},
{asin:"B0DLD7VCHT",name:"GoPets Double Row Undercoat Rake",category:"Coat care",icon:"🪮",detail:"A rake for appropriate thicker coats."},
{asin:"B0002AQPKW",name:"JW Pet GripSoft Undercoat Rake",category:"Coat care",icon:"🐾",detail:"A classic undercoat grooming rake."},
{asin:"B004UTDHP2",name:"Andis Stainless Steel Comb 65730",category:"Coat care",icon:"✨",detail:"A sturdy metal grooming comb."},
{asin:"B004Y5F77S",name:"Andis Stainless Steel Comb 65725",category:"Coat care",icon:"✨",detail:"A longer grooming comb for coat checks."},
{asin:"B081ZQV5CD",name:"Pet Teezer De-Shedding Brush",category:"Coat care",icon:"🪮",detail:"A hand-held brush for shedding coats."},
{asin:"B00079PHVG",name:"Earthbath Hypoallergenic Dog Shampoo",category:"Bath time",icon:"🛁",detail:"A fragrance-free shampoo option."},
{asin:"B00DTEV54Y",name:"Burt’s Bees Oatmeal Dog Shampoo",category:"Bath time",icon:"🫧",detail:"Oatmeal and honey dog shampoo."},
{asin:"B005IARU28",name:"Nature’s Specialties Hi-Con Shampoo",category:"Bath time",icon:"🧴",detail:"A concentrated grooming shampoo."},
{asin:"B00AO3N640",name:"Nature’s Specialties Almond Crisp Shampoo",category:"Bath time",icon:"🧴",detail:"A scented grooming shampoo."},
{asin:"B0002IEYIE",name:"Earthbath Vanilla Almond Shampoo",category:"Bath time",icon:"🛁",detail:"A vanilla-almond bath-day choice."},
{asin:"B0F22MZ685",name:"Burt’s Bees Oatmeal Shampoo + Conditioner",category:"Bath time",icon:"🧴",detail:"A combined wash-and-condition formula."},
{asin:"B06XG6B5JN",name:"CHI for Dogs Detangling Spray",category:"Coat care",icon:"✨",detail:"A leave-in coat finishing spray."},
{asin:"B000634IUO",name:"TropiClean Tangle Remover Spray",category:"Coat care",icon:"🫧",detail:"A detangling option between appointments."},
{asin:"B00VJM2MLI",name:"TropiClean Sweet Pea Detangler",category:"Coat care",icon:"🌸",detail:"A sweet-pea detangling spray."},
{asin:"B0GFGGY3F8",name:"TropiClean Detangling Conditioner",category:"Coat care",icon:"🧴",detail:"A spray conditioner for regular coat care."},
{asin:"B07PFCLHKR",name:"Casfuy Two-Speed Nail Grinder",category:"Paws & teeth",icon:"🐾",detail:"A rechargeable nail grinder."},
{asin:"B0BBL7DQNV",name:"Casfuy Six-Speed Nail Grinder",category:"Paws & teeth",icon:"🐾",detail:"An adjustable-speed nail grinder."},
{asin:"B00JENKK8Q",name:"Epica Pet Nail Clippers",category:"Paws & teeth",icon:"✂️",detail:"Clippers for small and medium pets."},
{asin:"B0002RJM8C",name:"Safari Professional Nail Trimmer",category:"Paws & teeth",icon:"✂️",detail:"A non-slip nail clipper option."},
{asin:"B0002ARQV4",name:"Safari Nail Trimmer, Alternate Size",category:"Paws & teeth",icon:"✂️",detail:"Another size of Safari nail trimmer."},
{asin:"B002PNIVAQ",name:"Millers Forge Doggy Man Nail Clipper",category:"Paws & teeth",icon:"✂️",detail:"A plier-style nail clipper."},
{asin:"B0111SLMUQ",name:"Millers Forge Nail Clipper with Stop",category:"Paws & teeth",icon:"✂️",detail:"A clipper with a safety stop."},
{asin:"B00CEY59L0",name:"Burt’s Bees Paw and Nose Lotion",category:"Paws & teeth",icon:"🐾",detail:"A lotion for everyday paw care."},
{asin:"B09V1XHHKX",name:"Pet Head On All Paws Butter",category:"Paws & teeth",icon:"🥥",detail:"A coconut-scented paw butter."},
{asin:"B0054WTPBY",name:"TropiClean Fresh Breath Water Additive",category:"Paws & teeth",icon:"🦷",detail:"A dental water additive; follow label directions."},
{asin:"B00025K0R6",name:"Petrodex Enzymatic Dog Toothpaste",category:"Paws & teeth",icon:"🦷",detail:"Dog toothpaste for brushing routines."},
{asin:"B07NHGX19F",name:"Earth Rated Dog Grooming Wipes",category:"Bath time",icon:"🧼",detail:"Wipes for quick cleanups."},
{asin:"B010MVG6ZY",name:"Pogi’s Hypoallergenic Grooming Wipes",category:"Bath time",icon:"🧼",detail:"An unscented wipe option."},
{asin:"B07C249HRJ",name:"Pogi’s Conditioning Dog Wipes",category:"Bath time",icon:"🧼",detail:"A second wipe option for paws and coats."},
{asin:"B01IRO7WR4",name:"Pet MD Ear Cleaning Wipes",category:"Bath time",icon:"👂",detail:"Wipes designed for outer-ear cleaning."},
{asin:"B01DO6AVR8",name:"Dog Gone Smart Dirty Dog Shammy",category:"Bath time",icon:"🧺",detail:"A microfiber towel for bath-day drying."},
{asin:"B00T7W30IG",name:"Bone Dry Microfiber Pet Towel",category:"Bath time",icon:"🧺",detail:"A lightweight dog-drying towel."},
{asin:"B0DMPM1Q3X",name:"WOUSEDO Microfiber Dog Towels",category:"Bath time",icon:"🧺",detail:"A two-pack towel option."},
{asin:"B0002AR0I8",name:"KONG Classic Dog Toy",category:"Play & everyday",icon:"🦴",detail:"A classic stuffable rubber toy; choose the right size."},
{asin:"B000GUDZO2",name:"KONG Extreme Dog Toy",category:"Play & everyday",icon:"🦴",detail:"A tougher rubber toy variant."},
{asin:"B00BSYR7K8",name:"Earth Rated Lavender Poop Bags",category:"Play & everyday",icon:"🛍️",detail:"Waste bags for everyday walks."},
{asin:"B00LAI9OM6",name:"Earth Rated Unscented Poop Bags",category:"Play & everyday",icon:"🛍️",detail:"An unscented waste-bag option."},
{asin:"B08VN2W5NC",name:"Earth Rated Poop Bag Holder",category:"Play & everyday",icon:"🐕",detail:"A dispenser for walks."},
{asin:"B0009F3MNS",name:"Hartz Groomer’s Best Combo Brush",category:"Coat care",icon:"🪮",detail:"A pin-and-bristle combo brush."},
{asin:"B000YIWVA0",name:"Safari Self-Cleaning Slicker Brush",category:"Coat care",icon:"🪮",detail:"A slicker brush with easy cleanup."},
{asin:"B01HRSZRXM",name:"oneisall Cordless Dog Clippers",category:"Coat care",icon:"✂️",detail:"At-home clippers for experienced handlers."},
{asin:"B01EFLKZ7C",name:"Round-Tip Pet Grooming Scissors",category:"Coat care",icon:"✂️",detail:"Rounded-tip scissors for careful grooming."},
{asin:"B003L1V2CU",name:"TropiClean Gentle Puppy Shampoo",category:"Bath time",icon:"🐶",detail:"A puppy bath-time option."},
{asin:"B000KEVF32",name:"GREENIES Original Dental Treats",category:"Paws & teeth",icon:"🦷",detail:"Dental chews; select a suitable size."},
{asin:"B07RYNKLPM",name:"WHIMZEES Brushzees Dental Treats",category:"Paws & teeth",icon:"🦷",detail:"A brush-shaped chew option."},
{asin:"B0CV9BQFHP",name:"LickiMat Classic Buddy",category:"Play & everyday",icon:"👅",detail:"A lick mat for treats and enrichment."},
{asin:"B07B9RQMBL",name:"Blue-9 Balance Harness",category:"Play & everyday",icon:"🐕",detail:"An adjustable harness for walks."},
{asin:"B0CGRXDY46",name:"Kurgo Tru-Fit Dog Car Harness",category:"Play & everyday",icon:"🚗",detail:"A travel harness; check the fit and instructions."},
{asin:"B0171MQTZE",name:"Voyager Step-In Air Harness",category:"Play & everyday",icon:"🐕",detail:"A step-in mesh harness option."},
{asin:"B01N64DCPR",name:"Dexas MudBuster Paw Cleaner",category:"Play & everyday",icon:"🐾",detail:"A portable paw-cleaning cup."},
{asin:"B00074L4RW",name:"PetSafe Gentle Leader Headcollar",category:"Play & everyday",icon:"🐕",detail:"A training headcollar; follow fitting instructions."},
{asin:"B0DVZQ1C4Y",name:"Nite Ize NiteDog Rechargeable Light",category:"Play & everyday",icon:"💡",detail:"A light for dusk and evening walks."},
{asin:"B06Y233F3Q",name:"Dog Gone Smart Dirty Dog Doormat",category:"Play & everyday",icon:"🧺",detail:"An absorbent entry mat for wet paws."},
{asin:"B00BAGTNAQ",name:"ChomChom Pet Hair Roller",category:"Play & everyday",icon:"🧹",detail:"A reusable roller for fur on furniture."},
{asin:"B07CB6RBSP",name:"Bissell Pet Hair Eraser Hand Vacuum",category:"Play & everyday",icon:"🧹",detail:"A handheld vacuum for pet-hair cleanup."}
];
const grid=document.querySelector('#product-grid');const items=document.querySelector('#cart-items');const cartCount=document.querySelector('#cart-count');const checkout=document.querySelector('#amazon-checkout');
const key='furever-fluffy-amazon-picks-v1';let cart={};try{const saved=JSON.parse(localStorage.getItem(key)||'{}');if(saved&&typeof saved==='object'&&!Array.isArray(saved))for(const p of products){const n=Number(saved[p.asin]);if(Number.isInteger(n)&&n>0)cart[p.asin]=Math.min(n,20)}}catch{}
const associateTag='fureverfluf0e-20';
const link=p=>`https://www.amazon.com/dp/${p.asin}?tag=${encodeURIComponent(associateTag)}`;
function save(){try{localStorage.setItem(key,JSON.stringify(cart))}catch{}}
function renderCart(){items.replaceChildren();let total=0;for(const p of products){const qty=cart[p.asin]||0;if(!qty)continue;total+=qty;const row=document.createElement('div');row.className='cart-item';const label=document.createElement('strong');label.textContent=p.name;const amazon=document.createElement('a');amazon.href=link(p);amazon.target='_blank';amazon.rel='noopener noreferrer';amazon.textContent='View on Amazon ↗';const controls=document.createElement('div');controls.className='cart-controls';for(const [text,delta,title] of [['−',-1,'Remove one'],['+',1,'Add one']]){const btn=document.createElement('button');btn.type='button';btn.textContent=text;btn.setAttribute('aria-label',`${title}: ${p.name}`);btn.addEventListener('click',()=>change(p.asin,delta));controls.append(btn);if(delta===-1){const q=document.createElement('span');q.textContent=String(qty);q.setAttribute('aria-label',`Quantity ${qty}`);controls.append(q)}}const remove=document.createElement('button');remove.className='remove';remove.type='button';remove.textContent='Remove';remove.setAttribute('aria-label',`Remove ${p.name}`);remove.addEventListener('click',()=>{delete cart[p.asin];save();renderCart()});controls.append(remove);row.append(label,amazon,controls);items.append(row)}if(!total){const empty=document.createElement('p');empty.className='cart-empty';empty.textContent='Your cart is waiting for a little puppy love. 🐾';items.append(empty)}cartCount.textContent=String(total);checkout.disabled=!total}
function change(asin,delta){const next=Math.max(0,Math.min(20,(cart[asin]||0)+delta));if(next)cart[asin]=next;else delete cart[asin];save();renderCart()}
function renderProducts(category='all'){grid.replaceChildren();for(const p of products){if(category!=='all'&&p.category!==category)continue;const card=document.createElement('article');card.className='product-card';const art=document.createElement('div');art.className='product-art';const artLink=document.createElement('a');artLink.href=link(p);artLink.target='_blank';artLink.rel='noopener noreferrer';artLink.setAttribute('aria-label',`View ${p.name} on Amazon`);const photo=document.createElement('img');photo.src=`Images/shop-products/${p.asin}.jpg`;photo.alt=p.name;photo.loading='lazy';artLink.append(photo);art.append(artLink);const body=document.createElement('div');body.className='product-content';const cat=document.createElement('span');cat.className='product-category';cat.textContent=p.category;const heading=document.createElement('h3');heading.textContent=p.name;const detail=document.createElement('p');detail.textContent=p.detail;const actions=document.createElement('div');actions.className='product-actions';const add=document.createElement('button');add.type='button';add.textContent='＋ Add to cart';add.setAttribute('aria-label',`Add ${p.name} to cart`);add.addEventListener('click',()=>change(p.asin,1));const amazon=document.createElement('a');amazon.href=link(p);amazon.target='_blank';amazon.rel='noopener noreferrer';amazon.textContent='View on Amazon ↗';actions.append(add,amazon);const price=document.createElement('a');price.className='product-price';price.href=link(p);price.target='_blank';price.rel='noopener noreferrer';price.textContent='See live price on Amazon ↗';body.append(cat,heading,detail,price,actions);card.append(art,body);grid.append(card)}}
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>{const selected=b===button;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected))});renderProducts(button.dataset.filter)}));
checkout.addEventListener('click',()=>{const selected=products.filter(p=>cart[p.asin]);if(!selected.length)return;const form=document.createElement('form');form.method='GET';form.action='https://www.amazon.com/gp/aws/cart/add.html';form.target='_blank';form.style.display='none';form.setAttribute('aria-hidden','true');const tagInput=document.createElement('input');tagInput.type='hidden';tagInput.name='AssociateTag';tagInput.value=associateTag;form.append(tagInput);selected.forEach((p,i)=>{for(const [name,value] of [[`ASIN.${i+1}`,p.asin],[`Quantity.${i+1}`,String(cart[p.asin])]]){const input=document.createElement('input');input.name=name;input.value=value;form.append(input)}});document.body.append(form);form.submit();form.remove()});
renderProducts();renderCart();
